# Explicit plain-POSIX-sh shell, deliberately: this justfile runs in
# this repo's Dev Container, GitHub Actions (bash-only ubuntu-latest
# runner), and homelab's migrate.py (Alpine, no zsh/bash installed for
# this package manager branch) - see deploys/apps.yaml's
# `migrate_command: "just db-migrate"`. `sh` is the one thing guaranteed
# present everywhere.
set dotenv-load := true
set dotenv-filename := ".env.local"
set shell := ["sh", "-eu", "-c"]

app := "slopyard"
image := "slopyard:local"
gocache := "/tmp/slopyard-go-build"
project := `basename "$(pwd)"`
db_name := env_var_or_default("POSTGRES_DB", "slopyard")

# Read from the Compose secret mount - only valid inside the Dev
# Container. Generated once per workspace by .devcontainer/generate-secrets.sh
# and reused across restarts/rebuilds; never regenerated by `just`.
#
# database_url/redis_url respect an already-set DATABASE_URL/REDIS_URL env
# var first: homelab's migrate.py sets a real DATABASE_URL (from the
# production k8s Secret) before running `just db-migrate`, which has no
# /run/secrets/* at all (that only exists in this workspace's own Compose
# containers). Always computing a local default unconditionally would
# silently override that and break production migrations - see
# link108/cutty-bangerz's justfile for the incident that taught us this.
postgres_user := `cat /run/secrets/postgres_user 2>/dev/null || true`
postgres_password := `cat /run/secrets/postgres_password 2>/dev/null || true`
redis_password := `cat /run/secrets/redis_password 2>/dev/null || true`
database_url := env_var_or_default("DATABASE_URL", "postgresql://" + postgres_user + ":" + postgres_password + "@postgres:5432/" + db_name + "?sslmode=disable")
redis_url := env_var_or_default("REDIS_URL", "redis://:" + redis_password + "@redis:6379/0")

default:
    @just --list

alias run := docker-run
alias stop := docker-stop
alias logs := docker-logs
alias migrate := db-migrate
alias seed := db-seed

# Create .env.local from the documented template when it does not exist.
env:
    @if [ ! -f .env.local ]; then cp .env.example .env.local; echo "Created .env.local"; else echo ".env.local already exists"; fi

# First-time setup inside a freshly created Dev Container. Postgres/Redis
# already exist by this point (devcontainer.json's initializeCommand +
# Compose health checks handle that before you get a shell).
setup: env
    @just db-setup
    @echo "Ready. Run: just dev"

docker-build:
    docker build -t {{image}} .

build:
    GOCACHE={{gocache}} go build ./cmd/slopyard ./cmd/migrate ./cmd/seed ./cmd/dbsetup

lint:
    GOCACHE={{gocache}} go vet ./...

typecheck:
    GOCACHE={{gocache}} go test -run '^$' ./...

# Same as CI.
alias ci := verify

verify: typecheck lint test build

dev: db-setup
    DATABASE_URL="{{database_url}}" REDIS_URL="{{redis_url}}" GOCACHE={{gocache}} go run ./cmd/slopyard

docker-run: docker-build
    -docker rm -f {{app}}
    docker run -d --name {{app}} --env-file .env -e DATABASE_URL="$${DOCKER_DATABASE_URL:-$$(printf '%s' "$$DATABASE_URL" | sed 's/localhost/host.docker.internal/')}" -e REDIS_URL="$${DOCKER_REDIS_URL:-$$(printf '%s' "$$REDIS_URL" | sed 's/localhost/host.docker.internal/')}" -p 8080:8080 --add-host=host.docker.internal:host-gateway {{image}}

docker-stop:
    -docker stop {{app}}
    -docker rm {{app}}

docker-logs:
    docker logs -f {{app}}

# Apply pending migrations to DATABASE_URL.
db-migrate:
    DATABASE_URL="{{database_url}}" GOCACHE={{gocache}} go run ./cmd/migrate up

# Ensure the app role/database exist (idempotent - no-op against this
# workspace's own Postgres, which already has both), then migrate.
db-setup:
    DATABASE_URL="{{database_url}}" GOCACHE={{gocache}} go run ./cmd/dbsetup
    @just db-migrate

db-reset:
    DATABASE_URL="{{database_url}}" GOCACHE={{gocache}} go run ./cmd/migrate down
    @just db-migrate

db-seed:
    DATABASE_URL="{{database_url}}" GOCACHE={{gocache}} go run ./cmd/seed

# Open a psql shell against DATABASE_URL.
psql:
    psql "{{database_url}}"

# Open a redis-cli shell against REDIS_URL.
redis-cli:
    redis-cli -u "{{redis_url}}"

test:
    GOCACHE={{gocache}} go test ./...

# --- Workspace lifecycle (run from the HOST, not inside the Dev Container -
# these need Docker access to manage the Compose project itself). Named
# `workspace-*` rather than the shorter `stop`/`logs` used elsewhere in
# this fleet: those names are already taken here by the docker-run/
# docker-stop/docker-logs aliases above, for testing the production
# image against a host-run Postgres/Redis - a different, pre-existing
# thing from this workspace's own Dev Container Postgres/Redis.

# Show this workspace's container status.
status:
    docker compose -f compose.dev.yml -p {{project}} ps

# Follow this workspace's container logs.
workspace-logs:
    docker compose -f compose.dev.yml -p {{project}} logs -f --tail=100

# Stop this workspace's containers. Preserves data volumes and generated
# credentials - resume with `devcontainer up` or `just dev`.
workspace-stop:
    docker compose -f compose.dev.yml -p {{project}} down

# DESTROYS this workspace's containers, data volumes, and generated
# credentials. Only ever touches THIS checkout's own resources (scoped by
# Compose project name, i.e. this directory's name) - never another
# worktree, repo, or workspace.
[confirm("This deletes ALL local data and credentials for this workspace. Continue?")]
destroy:
    @echo "Destroying workspace: {{project}}"
    docker compose -f compose.dev.yml -p {{project}} down -v
    rm -rf .devcontainer/secrets
    @echo "Workspace destroyed. Run 'devcontainer up' to start fresh with new credentials."
